language: python
python: "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq cython python-numexpr python-numpy python-yaml
install:
  - pip install flake8  # Not yet available in Debian stable
  - pip install tables  # For version > 3
  - pip install -e .
  - python setup.py build_ext --inplace
script: make test-ci
