# use container-based infrastructure
sudo: false

env:
  - USE_TRAVIS=true

language: python

python:
  - "2.7"

before_install:
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy,tables,cython numpy scipy tables numexpr matplotlib cython pyyaml larray

install:
  - pip install -e .
  - python setup.py build_ext --inplace

script:
  - make test-ci
